### PR TITLE
Adding node_env var for cidev

### PR DESCRIPTION
**Pull request by markpit**
The config.ts file https://github.com/companieshouse/restricted-word-web/blob/master/src/config.ts#L7 looks for a NODE_ENV var or defaults to 'development'

The Mesos global env file had a value of "test" for cidev, so this PR adds that value to cidev in ECS

### CODE REVIEW

**Comment by mwestacott** [comment]
Interesting, because I just checked Staging global_env and it doesn't set a value. Well, this is there but commented out:

`#export NODE_ENV='staging'`

So is Staging restricted-word-web running in Development mode?

**Comment by markpit** [comment]
> Interesting, because I just checked Staging global_env and it doesn't set a value. Well, this is there but commented out:
> 
> `#export NODE_ENV='staging'`
> 
> So is Staging restricted-word-web running in Development mode?

I guess so, perhaps that config.ts doesn't get used, plus node_env might only relate to what packages are used during build?

**Review by Zain-Abbas1 — APPROVED** [review]

**Comment by markpit** [comment]
it's used in App.ts:

if (config.env === "development") {
    logger.info("Configuring nunjucks for development mode");
    nunjucksConfig.watch = true;
    nunjucksConfig.noCache = true;
}

**Comment by mwestacott** [comment]
> it's used in App.ts:
> 
> if (config.env === "development") { logger.info("Configuring nunjucks for development mode"); nunjucksConfig.watch = true; nunjucksConfig.noCache = true; }

This does suggest we shouldn't be using the default value in Staging (or LIVE).

**Review by mwestacott — APPROVED** [review]

**Comment by markpit** [comment]
> > it's used in App.ts:
> > if (config.env === "development") { logger.info("Configuring nunjucks for development mode"); nunjucksConfig.watch = true; nunjucksConfig.noCache = true; }
> 
> This does suggest we shouldn't be using the default value in Staging (or LIVE).

I'd just replicate the values from those envs then we won't introduce any issues

**Pull request merged**
